### PR TITLE
Fix Django 1.11.2 None-descriptor bug

### PR DESCRIPTION
**Pull request by wlonk**
I couldn't get tests passing even before this change, so I've not added test coverage. If you can help me debug the test problems, I'll write some documentation on that, and get tests up for this change. Thanks!

### CODE REVIEW

**Comment by wlonk** [comment]
Thanks!

**Comment by nshafer** [comment]
Merged in, thank you very much. This fixes #7. Also updated tox config to force versions that duplicated this bug (Django 1.11.2 specifically).

**Comment by nshafer** [comment]
BTW, not sure why your tests are failing. I wrote a new test that catches it, so no worries. If you want to still debug, can you post what error you're getting?

**Comment by wlonk** [comment]
Thanks but it's not crucial right now. I'll ping you if I start work on another patch, though!

**Pull request merged**
