### PR TITLE
Add pickling + int/long equality

### PR DESCRIPTION
**Pull request by olegpesok**
- Adds the ability to pickle and unpickle an instance of a HashId
- Adds equality for `int` type: `int(a) == a`
- Adds equality for `long` type: `long(a) == a`
- Adds typecase to `long`

### CODE REVIEW

**Comment by nshafer** [comment]
Thanks for the patch, just one problem... `long` was removed from python3, so this patch only passes my python2 tests. Would it be possible to make this compatible with python3 as well? I want the module to support both.

**Comment by danie1k** [comment]
Hi @nshafer,
could you please merge this (or similar) fix? It's very important, because issue with pickle causes this field to be uncacheable by django caches:
```
PicklingError: Can't pickle <function Hashids.decode at 0x7fbc169bcb70>: it's not the same object as hashids.Hashids.decode
```

**Comment by nshafer** [comment]
I can't merge this as-is as it breaks in Python3, but I will attempt to get it fixed up myself.

**Comment by nshafer** [comment]
Merged, will be in version 2.1

**Pull request merged**
